# Generated by Django 6.0.7 on 2026-08-05 07:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cycle_number', models.PositiveIntegerField(help_text='The position/turn in the AJO cycle')),
                ('expected_payout_date', models.DateField()),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_schedules', to='contributions.contributiongroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts_due', to='contributions.groupmembership')),
            ],
            options={
                'ordering': ['cycle_number'],
                'unique_together': {('group', 'cycle_number')},
            },
        ),
    ]
