# Generated by Django 6.0.7 on 2026-08-06 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0004_payoutschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiongroup',
            name='cycle_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='contributiongroup',
            name='deadline_day',
            field=models.IntegerField(default=1, help_text='The day of the week or month the deadline falls on.'),
        ),
        migrations.AddField(
            model_name='contributiongroup',
            name='deadline_time',
            field=models.TimeField(default='12:00:00', help_text='The exact time of day the system will auto-deduct (e.g., 18:00:00 for 6 PM).'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='next_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The exact date and time the auto-deduction runs'),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='next_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The exact date and time the auto-deduction runs'),
        ),
    ]
