# Generated by Django 6.0.7 on 2026-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0005_contributiongroup_cycle_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='current_cycle_number',
            field=models.IntegerField(default=1, help_text='Tracks which cycle the user is currently paying for.'),
        ),
    ]
