# Generated by Django 6.0.7 on 2026-08-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0006_groupmembership_current_cycle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cycle_number',
            field=models.IntegerField(blank=True, help_text='The Ajo cycle this payment covers', null=True),
        ),
    ]
