# Generated by Django 6.0.7 on 2026-08-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0007_transaction_cycle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiongroup',
            name='daily_fine_percentage',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='The daily percentage fine levied on defaulters (e.g., 2.00 for 2%).', max_digits=5),
        ),
    ]
