# Generated by Django 6.0.7 on 2026-09-22 01:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0009_transaction_user_alter_transaction_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutschedule',
            name='invested_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Actual amount moved into the investment vault upon payout.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payoutschedule',
            name='investment_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of payout automatically routed to investment vault (0 to 100%).', max_digits=5),
        ),
        migrations.CreateModel(
            name='InvestmentVault',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_annual', models.DecimalField(decimal_places=2, default=12.0, max_digits=5)),
                ('lock_duration_days', models.PositiveIntegerField(default=90)),
                ('is_matured', models.BooleanField(default=False)),
                ('payout_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='contributions.payoutschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
