# Generated by Django 6.0.7 on 2026-09-29 11:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0010_payoutschedule_invested_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiongroup',
            name='alajo_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='The Alajo commission fee percentage deducted upon payout distribution (e.g., 2.00 for 2%).', max_digits=5),
        ),
    ]
