# Generated by Django 6.0.7 on 2026-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0011_contributiongroup_alajo_fee_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_active',
            field=models.BooleanField(default=False, help_text="Active is True only when status is 'approved'"),
        ),
    ]
