# Generated by Django 6.0.7 on 2026-10-03 11:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0012_groupmembership_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributiongroup',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
