from django.urls import path
from .views import (
    VerifyIdentityLookupView,
    SubmitAddressTier2View,
    SendOTPView,
    UserNotificationListView,
    UserNotificationCountView,
    VerifyOTPView,
    CompleteOnboardingRegistrationView,
    RegisterUserView,
    WalletDetailView,
    CreateWithdrawalRequestView,
    InvestmentLockListView,
    LiquidateInvestmentView,
    SubmitKYCView,
    UserProfileView,
    VerifyFaceMatchView,
    SubmitAddressTier2WithDocumentView,
    KYCStatusView,
    ChangePasswordView,
    UserPreferencesView,
    LogoutView,
)

urlpatterns = [
    path('onboarding/send-otp/', SendOTPView.as_view(), name='send-otp'),
    path('onboarding/verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('onboarding/complete/', CompleteOnboardingRegistrationView.as_view(), name='complete-onboarding'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('wallet/', WalletDetailView.as_view(), name='wallet-detail'),
    path('kyc/verify-identity/', VerifyIdentityLookupView.as_view(), name='kyc-verify-identity'),
    path('kyc/submit-address/', SubmitAddressTier2View.as_view(), name='kyc-submit-address'),
    path('withdrawals/', CreateWithdrawalRequestView.as_view(), name='create-withdrawal'),
    path('investments/', InvestmentLockListView.as_view(), name='investment-locks'),
    path('investments/<uuid:lock_id>/liquidate/', LiquidateInvestmentView.as_view(), name='liquidate-investment'),
    path('kyc/submit/', SubmitKYCView.as_view(), name='kyc-submit'),
    path('kyc/verify-face/', VerifyFaceMatchView.as_view(), name='kyc-verify-face'),
    path('kyc/submit-address-document/', SubmitAddressTier2WithDocumentView.as_view(), name='kyc-submit-address-doc'),
    path('kyc/status/', KYCStatusView.as_view(), name='kyc-status'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('profile/', UserProfileView.as_view(), name='user-profile'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('preferences/', UserPreferencesView.as_view(), name='user-preferences'),
    path('notifications/', UserNotificationListView.as_view(), name='user-notifications'),
    path('notifications/unread-count/', UserNotificationCountView.as_view(), name='user-notifications-count'),
    path('logout/', LogoutView.as_view(), name='user-logout'),
]