# Generated by Django 6.0.7 on 2026-08-06 04:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('annual_interest_rate', models.DecimalField(decimal_places=4, default=0.15, max_digits=5)),
                ('locked_date', models.DateField(auto_now_add=True)),
                ('maturity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active - Yielding Interest'), ('matured', 'Matured - Successfully Completed'), ('liquidated_early', 'Liquidated Early - Penalized')], default='active', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_locks', to='users.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_percentage', models.PositiveIntegerField(default=0, help_text='Percentage of the total amount to route to the Wealth Engine.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('destination_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_account', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='users.wallet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
