# Generated by Django 6.0.7 on 2026-09-21 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_investmentlock_withdrawalrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
