# Generated by Django 6.0.7 on 2026-09-22 02:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bvn_nin_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_tier',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='investment_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Percentage of total amount to route to the Wealth Engine.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
