# Generated by Django 6.0.7 on 2026-09-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=100, help_text='Dynamic user trust score (0-100)'),
        ),
    ]
