# Generated by Django 6.0.7 on 2026-09-29 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=10)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_reference', models.CharField(max_length=100)),
                ('name_similarity_score', models.FloatField()),
                ('matched_legal_name', models.CharField(max_length=255)),
                ('registered_name', models.CharField(max_length=255)),
                ('match_passed', models.BooleanField(default=False)),
                ('raw_response_digest', models.CharField(max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserKYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveSmallIntegerField(choices=[(0, 'Tier 0 - Unverified'), (1, 'Tier 1 - Basic (BVN or vNIN)'), (2, 'Tier 2 - Medium (Dual BVN+vNIN & Residential Address)'), (3, 'Tier 3 - Full KYC (Proof of Address & Enhanced Due Diligence)')], default=0)),
                ('bvn_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('bvn_masked', models.CharField(blank=True, max_length=16, null=True)),
                ('vnin_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('vnin_masked', models.CharField(blank=True, max_length=16, null=True)),
                ('has_bvn_verified', models.BooleanField(default=False)),
                ('has_nin_verified', models.BooleanField(default=False)),
                ('residential_address', models.TextField(blank=True, null=True)),
                ('address_verified', models.BooleanField(default=False)),
                ('ndpa_consent_granted', models.BooleanField(default=False)),
                ('ndpa_consent_timestamp', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
