# Generated by Django 6.0.7 on 2026-09-29 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_kycauditlog_userkycprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userkycprofile',
            name='face_match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkycprofile',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userkycprofile',
            name='selfie_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
        migrations.AddField(
            model_name='userkycprofile',
            name='utility_bill',
            field=models.FileField(blank=True, null=True, upload_to='kyc/utility_bills/'),
        ),
        migrations.AddField(
            model_name='userkycprofile',
            name='utility_bill_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
