# Generated by Django 6.0.7 on 2026-09-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userkycprofile_face_match_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryRegistrationVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(db_index=True, max_length=255, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Temporary Registration Verification',
                'verbose_name_plural': 'Temporary Registration Verifications',
            },
        ),
    ]
